/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GameOverView.java
 *
 * Created on May 8, 2011, 3:38:45 PM
 */

package edu.ycp.cs320.Stratego;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author sandrew3
 */
public class GameOverView extends javax.swing.JPanel {
    private final ActionListener quitButtonActionListener;
    private final ActionListener newGameButtonActionListener;

    private SetupView setupView;
    private GameInstance gameInt;

    /** Creates new form GameOverView */
    public GameOverView(SetupView setupView, GameInstance gameInt) {
        
        this.setVisible(true); // this should allow the this panel to be seen
        this.setupView = setupView;
        this.gameInt = gameInt;

        quitButtonActionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleQuitButtonPressed(e);
            }


        };
        newGameButtonActionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleNewGameButtonPressed(e);
            }


        };
        
        initComponents();

        if(gameInt.getWinner() == 1)
        {
        	setupView.setEnabled(false);
            gameOverText.setText("You Win!!!");
        }
        else if(gameInt.getWinner() == 2)
        {
        	setupView.setEnabled(false);
            gameOverText.setText("You Lose. T-T");
        }
        else if(gameInt.getWinner() == 0)
        {
        	gameOverText.setText("BATTLE!");
        	quitButton.setEnabled(false);
        	newGameButton.setEnabled(false);
        	
        	if(setupView.getGameInt().getOne() != null)
        	{
	        	Piece attacking = setupView.getGameInt().getOne();
	        	Piece defending = setupView.getGameInt().getTwo();
	        	
	        	newGameButton.setText(attacking.get_Value().toString());
	        	quitButton.setText(defending.get_Value().toString());
	    	
	    	
	        	if(attacking.get_isHuman()) // set newGameButton's Color to match the it's owner
	        	{		
	        		newGameButton.setBackground(Color.CYAN);
	        		quitButton.setBackground(Color.ORANGE);
	        	}
	        	else
	        	{
	        		newGameButton.setBackground(Color.ORANGE);
	        		quitButton.setBackground(Color.CYAN);
	        	}
        	}
        	
        	setupView.getGameInt().wait(4);
        	this.setVisible(false);
        	
        	
        	
        }
        else
        {
            gameOverText.setText("Da Hell You Do???");
        }
    }

    private void handleQuitButtonPressed(ActionEvent e) {
         System.exit(2);
    }

    private void handleNewGameButtonPressed(ActionEvent e) {
         Game newGame = new Game();
         setupView.setVisible(false);
         this.setVisible(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameOverText = new javax.swing.JLabel();
        newGameButton = new javax.swing.JButton();
        newGameButton.addActionListener(newGameButtonActionListener);
        quitButton = new javax.swing.JButton();
        quitButton.addActionListener(quitButtonActionListener);

        gameOverText.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        gameOverText.setText("jLabel1");

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(gameOverText)
                .addGap(157, 157, 157))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(gameOverText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newGameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newGameButtonActionPerformed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            GameInstance x = new GameInstance();
            SetupView setupView = new SetupView(x);
            public void run() {
                new GameOverView(setupView, x).setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameOverText;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables

    
    
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            GameInstance x = new GameInstance();
//            public void run() {
//                new SetupView(x).setVisible(true);
//            }
//        });
//    }

}
